import { defaultProps } from './defaultProps';

test('should match the snapshot', () => {
  expect(defaultProps).toMatchInlineSnapshot(`
    {
      "classNames": {
        "button": "rdp-button",
        "button_reset": "rdp-button_reset",
        "caption_between": "rdp-caption_between",
        "caption_dropdowns": "rdp-caption_dropdowns",
        "caption_end": "rdp-caption_end",
        "caption_label": "rdp-caption_label",
        "caption_start": "rdp-caption_start",
        "day_disabled": "rdp-day_disabled",
        "day_gridcell": "rdp-day",
        "day_hidden": "rdp-day_hidden",
        "day_outside": "rdp-day_outside",
        "day_range_end": "rdp-day_range_end",
        "day_range_middle": "rdp-day_range_middle",
        "day_range_start": "rdp-day_range_start",
        "day_selected": "rdp-day_selected",
        "day_today": "rdp-day_today",
        "dropdown": "rdp-dropdown",
        "dropdown_icon": "rdp-dropdown_icon",
        "dropdown_month": "rdp-dropdown_month",
        "dropdown_year": "rdp-dropdown_year",
        "head": "rdp-head",
        "month": "rdp-month",
        "month_caption": "rdp-caption",
        "month_grid": "rdp-table",
        "months_wrapper": "rdp-months",
        "multiple_months": "rdp-multiple_months",
        "nav": "rdp-nav",
        "nav_button": "rdp-nav_button",
        "nav_button_next": "rdp-nav_button_next",
        "nav_button_previous": "rdp-nav_button_previous",
        "nav_icon": "rdp-nav_icon",
        "root": "rdp",
        "tbody": "rdp-tbody",
        "tfoot": "rdp-tfoot",
        "vhidden": "rdp-vhidden",
        "week_row": "rdp-row",
        "weekdays_row": "rdp-head_row",
        "weeknumber": "rdp-weeknumber",
        "weeknumber_rowheader": "rdp-head_cell",
        "with_weeknumber": "rdp-with_weeknumber",
      },
      "dataAttributes": {},
      "formatters": {
        "formatCaption": [Function],
        "formatDay": [Function],
        "formatMonthCaption": [Function],
        "formatWeekNumber": [Function],
        "formatWeekdayName": [Function],
        "formatYearCaption": [Function],
      },
      "labels": {
        "labelDay": [Function],
        "labelGrid": [Function],
        "labelMonthDropdown": [Function],
        "labelNext": [Function],
        "labelPrevious": [Function],
        "labelWeekNumber": [Function],
        "labelWeekday": [Function],
        "labelYearDropdown": [Function],
      },
      "locale": {
        "code": "en-US",
        "formatDistance": [Function],
        "formatLong": {
          "date": [Function],
          "dateTime": [Function],
          "time": [Function],
        },
        "formatRelative": [Function],
        "localize": {
          "day": [Function],
          "dayPeriod": [Function],
          "era": [Function],
          "month": [Function],
          "ordinalNumber": [Function],
          "quarter": [Function],
        },
        "match": {
          "day": [Function],
          "dayPeriod": [Function],
          "era": [Function],
          "month": [Function],
          "ordinalNumber": [Function],
          "quarter": [Function],
        },
        "options": {
          "firstWeekContainsDate": 1,
          "weekStartsOn": 0,
        },
      },
      "modifiers": {},
      "modifiersClassNames": {},
      "modifiersStyles": {},
      "numberOfMonths": 1,
      "showOutsideDays": false,
      "styles": {},
      "today": 2023-07-18T05:00:00.000Z,
    }
  `);
});
