declare const styles: {
  'root': string
  'vhidden': string
  'with_weeknumber': string
  'months_wrapper': string
  'caption': string
  'multiple_months': string
  'caption_dropdowns': string
  'caption_label': string
  'nav': string
  'caption_start': string
  'caption_end': string
  'nav_button': string
  'dropdown_year': string
  'dropdown_month': string
  'dropdown': string
  'dropdown_icon': string
  'head': string
  'head_row': string
  'row': string
  'head_cell': string
  'tbody': string
  'footer': string
  'cell': string
  'weeknumber_rowheader': string
  'day': string
  'day_today': string
  'day_outside': string
  'day_selected': string
  'day_disabled': string
  'day_hidden': string
  'rdp': string
  'day_range_start': string
  'day_range_end': string
  'day_range_middle': string
  'weekdays_row': string
  'weekday_columnheader': string
  'week_row': string
  'month_grid_wrapper': string
  'month_rowgroup': string
  'month_grid': string
  'month_caption': string
  'caption_between': string
  'nav_button_previous': string
  'nav_button_next': string
  'nav_icon': string
}

export default styles
